-- Fuel Smart database schema.
-- Apply this file manually from the Supabase SQL Editor. Every statement is
-- idempotent, so it is safe to use when bootstrapping an empty project.

-- Official MIMIT station registry. mimit_id is the stable source identifier.
create table if not exists public.stations (
  id bigint generated by default as identity primary key,
  mimit_id bigint not null unique,
  manager text,
  brand text,
  station_type text,
  name text,
  address text,
  city text,
  province text,
  latitude double precision,
  longitude double precision,
  source_updated_at timestamptz,
  updated_at timestamptz not null default now()
);

-- Latest fuel prices for each station, fuel type, and service mode.
-- Prices are removed automatically when their station is deleted.
create table if not exists public.fuel_prices (
  id bigint generated by default as identity primary key,
  station_id bigint not null
    references public.stations(id)
    on delete cascade,
  fuel_type text not null,
  price numeric(6,3) not null,
  is_self boolean not null,
  communicated_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (station_id, fuel_type, is_self)
);

-- Supports the future geographic pre-filter by latitude and longitude.
create index if not exists stations_coordinates_idx
on public.stations(latitude, longitude);

-- Speeds up joins and lookups of all prices belonging to one station.
create index if not exists fuel_prices_station_id_idx
on public.fuel_prices(station_id);

-- Supports price searches by fuel, service mode, and amount.
create index if not exists fuel_prices_lookup_idx
on public.fuel_prices(fuel_type, is_self, price);
