-- Fuel Smart database schema.
-- Apply this file manually from the Supabase SQL Editor. Every statement is
-- idempotent, so it is safe to use when bootstrapping an empty project.

-- Official MIMIT station registry. mimit_id is the stable source identifier.
create table if not exists public.stations (
  id bigint generated by default as identity primary key,
  mimit_id bigint not null unique,
  manager text,
  brand text,
  station_type text,
  name text,
  address text,
  city text,
  province text,
  latitude double precision,
  longitude double precision,
  source_updated_at timestamptz,
  updated_at timestamptz not null default now()
);

-- Latest fuel prices for each station, fuel type, and service mode.
-- Prices are removed automatically when their station is deleted.
create table if not exists public.fuel_prices (
  id bigint generated by default as identity primary key,
  station_id bigint not null
    references public.stations(id)
    on delete cascade,
  fuel_type text not null,
  price numeric(6,3) not null,
  is_self boolean not null,
  communicated_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (station_id, fuel_type, is_self)
);

-- PostGIS is installed in the dedicated gis schema in the Supabase project.
-- ADD COLUMN IF NOT EXISTS also upgrades databases created from an older copy
-- of this file without disturbing their existing stations.
alter table public.stations
add column if not exists location gis.geography(Point, 4326);

-- Supports the future geographic pre-filter by latitude and longitude.
create index if not exists stations_coordinates_idx
on public.stations(latitude, longitude);

-- Supports efficient proximity searches using the PostGIS geography column.
create index if not exists stations_location_gix
on public.stations using gist(location);

-- Keeps the derived geography point aligned with the MIMIT coordinates.
create or replace function public.update_station_location()
returns trigger
language plpgsql
as $$
begin
  if new.latitude is null or new.longitude is null then
    new.location := null;
  else
    new.location := gis.st_setsrid(
      gis.st_makepoint(new.longitude, new.latitude),
      4326
    )::gis.geography;
  end if;

  return new;
end;
$$;

create or replace trigger stations_update_location
before insert or update of latitude, longitude on public.stations
for each row
execute function public.update_station_location();

-- The server-side MIMIT importer writes stations as service_role, so its
-- upserts execute the location trigger under that role. Because PostGIS lives
-- in gis, the importer needs schema access and permission to call its routines.
GRANT USAGE ON SCHEMA gis TO service_role;
GRANT ALL ON ALL ROUTINES IN SCHEMA gis TO service_role;

-- Speeds up joins and lookups of all prices belonging to one station.
create index if not exists fuel_prices_station_id_idx
on public.fuel_prices(station_id);

-- Supports price searches by fuel, service mode, and amount.
create index if not exists fuel_prices_lookup_idx
on public.fuel_prices(fuel_type, is_self, price);
